default = "duckduck"
bing = "https://bing.com/search?q="
duckduck = "https://duckduckgo.com/?q="
google = "https://www.google.com/search?q="
maps = "https://www.google.com/maps/place/"
startpage = "https://www.startpage.com/sp/search?q="
